/*
 * Name and Student ID: Abdulmalik Alnasra(15897596) , Akshay Silswal(22163010) 
 * Course Code/Stream: COMP603/W101A
 * Program Design and Construction
 * Project Group 150
 * Project 2
 */

package Payment;
import javax.swing.JOptionPane;

public class ShippingInformation extends javax.swing.JFrame {

    /**
     * Creates new form ShippingInformation
     */
    public ShippingInformation() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaymentTopText = new javax.swing.JLabel();
        PaymentBox = new javax.swing.JPanel();
        ShoppingCartText = new javax.swing.JLabel();
        ShippingInformationText = new javax.swing.JLabel();
        AddressText = new javax.swing.JLabel();
        AddressTextBox = new javax.swing.JScrollPane();
        AddressTextArea = new javax.swing.JTextArea();
        CashOnDeliveryText = new javax.swing.JLabel();
        CashOnDeliverySelectButton = new javax.swing.JRadioButton();
        PayViaCardText = new javax.swing.JLabel();
        PayViaCardSelectButton = new javax.swing.JRadioButton();
        PayButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PaymentTopText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PaymentTopText.setText("Payment");

        PaymentBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ShoppingCartText.setText("Shopping Cart");

        ShippingInformationText.setText("Shipping Information:");

        AddressText.setText("Address:");

        AddressTextArea.setColumns(20);
        AddressTextArea.setRows(5);
        AddressTextBox.setViewportView(AddressTextArea);

        CashOnDeliveryText.setText("Cash On Delivery");

        CashOnDeliverySelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashOnDeliverySelectButtonActionPerformed(evt);
            }
        });

        PayViaCardText.setText("Pay Via Card");

        PayViaCardSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayViaCardSelectButtonActionPerformed(evt);
            }
        });

        PayButton.setText("Go");
        PayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaymentBoxLayout = new javax.swing.GroupLayout(PaymentBox);
        PaymentBox.setLayout(PaymentBoxLayout);
        PaymentBoxLayout.setHorizontalGroup(
            PaymentBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentBoxLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(PaymentBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PaymentBoxLayout.createSequentialGroup()
                        .addComponent(ShippingInformationText)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PaymentBoxLayout.createSequentialGroup()
                        .addGroup(PaymentBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PaymentBoxLayout.createSequentialGroup()
                                .addComponent(AddressText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddressTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                            .addGroup(PaymentBoxLayout.createSequentialGroup()
                                .addComponent(CashOnDeliveryText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CashOnDeliverySelectButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PayViaCardText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PayViaCardSelectButton)))
                        .addGap(71, 71, 71))))
            .addGroup(PaymentBoxLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(ShoppingCartText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaymentBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PayButton)
                .addGap(190, 190, 190))
        );
        PaymentBoxLayout.setVerticalGroup(
            PaymentBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentBoxLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ShoppingCartText)
                .addGap(14, 14, 14)
                .addComponent(ShippingInformationText)
                .addGroup(PaymentBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentBoxLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddressText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaymentBoxLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(AddressTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(PaymentBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PayViaCardText)
                    .addComponent(PayViaCardSelectButton)
                    .addGroup(PaymentBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CashOnDeliveryText)
                        .addComponent(CashOnDeliverySelectButton)))
                .addGap(32, 32, 32)
                .addComponent(PayButton)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PaymentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PaymentTopText)
                        .addGap(218, 218, 218))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(PaymentTopText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PaymentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CashOnDeliverySelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashOnDeliverySelectButtonActionPerformed
        // TODO add your handling code here:
        PayViaCardSelectButton.setSelected(false);
    }//GEN-LAST:event_CashOnDeliverySelectButtonActionPerformed

    private void PayViaCardSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayViaCardSelectButtonActionPerformed
        // TODO add your handling code here:
        CashOnDeliverySelectButton.setSelected(false);
    }//GEN-LAST:event_PayViaCardSelectButtonActionPerformed

    private void PayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayButtonActionPerformed
        // TODO add your handling code here:
        if (CashOnDeliverySelectButton.isSelected()) {
        // Handle cash on delivery
        
        JOptionPane.showMessageDialog(this, "Thank You for Shopping.\n Visit Again! ");
        dispose();
        
    } else if (PayViaCardSelectButton.isSelected()) {
        // Handle payment via card
        // Open the PaymentPortal frame
        PaymentPortal paymentPortalFrame = new PaymentPortal();
        paymentPortalFrame.setVisible(true);
        // Close the current frame
        dispose();
    }
    }//GEN-LAST:event_PayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShippingInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShippingInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShippingInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShippingInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShippingInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressText;
    private javax.swing.JTextArea AddressTextArea;
    private javax.swing.JScrollPane AddressTextBox;
    private javax.swing.JRadioButton CashOnDeliverySelectButton;
    private javax.swing.JLabel CashOnDeliveryText;
    private javax.swing.JButton PayButton;
    private javax.swing.JRadioButton PayViaCardSelectButton;
    private javax.swing.JLabel PayViaCardText;
    private javax.swing.JPanel PaymentBox;
    private javax.swing.JLabel PaymentTopText;
    private javax.swing.JLabel ShippingInformationText;
    private javax.swing.JLabel ShoppingCartText;
    // End of variables declaration//GEN-END:variables
}
