/*
 * Name and Student ID: Abdulmalik Alnasra(15897596) , Akshay Silswal(22163010) 
 * Course Code/Stream: COMP603/W101A
 * Program Design and Construction
 * Project Group 150
 * Project 2
 */
package Administrator;

import Login.Login;
import Payment.ShippingInformation;
import Database.DBManager;
import Database.CartAndBillSQLTables;
import java.sql.Statement;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ShoppingMain_Administrator extends javax.swing.JFrame {

    /**
     * Creates new form shop
     */
    public ShoppingMain_Administrator() {
        initComponents();
        Connect();
    }

    Connection con;
    PreparedStatement pat;
    PreparedStatement pat1;
    ResultSet rs;
    DefaultTableModel df;

    public void Connect() {
        try {
            con = DBManager.getConnection();
            con = DriverManager.getConnection("jdbc:derby:OnlineShopping_db");
            CartAndBillSQLTables cartandbilltables = new CartAndBillSQLTables();
            cartandbilltables.createCartAndBillTablesIfNotExists(con);

        } catch (SQLException ex) {
            Logger.getLogger(ShoppingMain_Administrator.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void sales() {
        String totcost = TotalCostBox.getText();
        String tpay = PayBox.getText();
        String bal = BalanceBox.getText();

        int lastid = 0;

        try {

            String query = "insert into bill(subtotal, pay, balance)values(?,?,?)";
            pat = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            pat.setString(1, totcost);
            pat.setString(2, tpay);
            pat.setString(3, bal);
            pat.executeUpdate();
            rs = pat.getGeneratedKeys();

            if (rs.next()) {
                lastid = rs.getInt(1);
            }
            int rows = jTable1.getRowCount();

            String query1 = "insert into cart( itemname, brandname, modelname, price, quantity, total)values(?,?,?,?,?,?)";
            pat1 = con.prepareStatement(query1);

            String iname = "";
            String ibname = "";
            String imname = "";
            String iprice;
            String qty;
            float itotal = 0;

            for (int i = 0; i < jTable1.getRowCount(); i++) {
                iname = (String) jTable1.getValueAt(i, 1);
                ibname = (String) jTable1.getValueAt(i, 2);
                imname = (String) jTable1.getValueAt(i, 3);
                iprice = (String) jTable1.getValueAt(i, 4);
                qty = (String) jTable1.getValueAt(i, 5);
                itotal = (float) jTable1.getValueAt(i, 6);

                //
                pat1.setString(1, iname);
                pat1.setString(2, ibname);
                pat1.setString(3, imname);
                pat1.setString(4, iprice);
                pat1.setString(5, qty);
                pat1.setFloat(6, itotal);
                pat1.executeUpdate();

            }

        } catch (SQLException ex) {
            Logger.getLogger(ShoppingMain_Administrator.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainAdministratorTextTop = new javax.swing.JLabel();
        AdministratorDetailsBox = new javax.swing.JPanel();
        ItemIDText = new javax.swing.JLabel();
        ItemIDBox = new javax.swing.JTextField();
        BillText = new javax.swing.JLabel();
        ItemNameText = new javax.swing.JLabel();
        ItemNameBox = new javax.swing.JTextField();
        TotalCostText = new javax.swing.JLabel();
        TotalCostBox = new javax.swing.JTextField();
        BrandNameText = new javax.swing.JLabel();
        BrandNameBox = new javax.swing.JTextField();
        AdministratorPayText = new javax.swing.JLabel();
        PayBox = new javax.swing.JTextField();
        ModelNameText = new javax.swing.JLabel();
        ModelNameBox = new javax.swing.JTextField();
        BalanceText = new javax.swing.JLabel();
        BalanceBox = new javax.swing.JTextField();
        PriceText = new javax.swing.JLabel();
        PriceBox = new javax.swing.JTextField();
        PrintInvoiceButton = new javax.swing.JButton();
        QuantityText = new javax.swing.JLabel();
        QuantityChangeButton = new javax.swing.JSpinner();
        AddToCartButton = new javax.swing.JButton();
        GoBackButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        ShoppingCartText = new javax.swing.JLabel();
        ShoppingCartScrollPanel = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainAdministratorTextTop.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MainAdministratorTextTop.setText("Online Shopping (Administrator)");

        AdministratorDetailsBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ItemIDText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ItemIDText.setText("Item ID:");

        ItemIDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemIDBoxActionPerformed(evt);
            }
        });
        ItemIDBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ItemIDBoxKeyPressed(evt);
            }
        });

        BillText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BillText.setText("Shopping Bill");

        ItemNameText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ItemNameText.setText("Item Name:");

        TotalCostText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TotalCostText.setText("Total Cost:");

        TotalCostBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalCostBoxActionPerformed(evt);
            }
        });

        BrandNameText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BrandNameText.setText("Brand Name:");

        AdministratorPayText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdministratorPayText.setText("Pay:");

        PayBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayBoxActionPerformed(evt);
            }
        });

        ModelNameText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ModelNameText.setText("Model Name:");

        BalanceText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BalanceText.setText("Balance:");

        BalanceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceBoxActionPerformed(evt);
            }
        });

        PriceText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PriceText.setText("Price:");

        PrintInvoiceButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PrintInvoiceButton.setText("Go");
        PrintInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintInvoiceButtonActionPerformed(evt);
            }
        });

        QuantityText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        QuantityText.setText("Quantity:");

        AddToCartButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AddToCartButton.setText("Add to Cart");
        AddToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCartButtonActionPerformed(evt);
            }
        });

        GoBackButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        GoBackButton.setText("Go Back");
        GoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonActionPerformed(evt);
            }
        });

        LogOutButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LogOutButton.setText("Log Out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdministratorDetailsBoxLayout = new javax.swing.GroupLayout(AdministratorDetailsBox);
        AdministratorDetailsBox.setLayout(AdministratorDetailsBoxLayout);
        AdministratorDetailsBoxLayout.setHorizontalGroup(
            AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdministratorDetailsBoxLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ItemIDText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ItemNameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BrandNameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModelNameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PriceText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuantityText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdministratorDetailsBoxLayout.createSequentialGroup()
                        .addGroup(AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ItemIDBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(ItemNameBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BrandNameBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ModelNameBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PriceBox, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdministratorDetailsBoxLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(BillText, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))
                            .addGroup(AdministratorDetailsBoxLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AdministratorDetailsBoxLayout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(PrintInvoiceButton))
                                    .addGroup(AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(AdministratorDetailsBoxLayout.createSequentialGroup()
                                            .addComponent(GoBackButton)
                                            .addGap(18, 18, 18)
                                            .addComponent(LogOutButton)
                                            .addGap(31, 31, 31))
                                        .addGroup(AdministratorDetailsBoxLayout.createSequentialGroup()
                                            .addGroup(AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TotalCostText, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                                .addComponent(AdministratorPayText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BalanceText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TotalCostBox)
                                                .addComponent(PayBox)
                                                .addComponent(BalanceBox, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))))))
                    .addGroup(AdministratorDetailsBoxLayout.createSequentialGroup()
                        .addComponent(QuantityChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddToCartButton)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        AdministratorDetailsBoxLayout.setVerticalGroup(
            AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdministratorDetailsBoxLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemIDText)
                    .addComponent(ItemIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BillText))
                .addGap(18, 18, 18)
                .addGroup(AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemNameText)
                    .addComponent(ItemNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalCostText)
                    .addComponent(TotalCostBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BrandNameText)
                    .addComponent(BrandNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdministratorPayText))
                .addGap(18, 18, 18)
                .addGroup(AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModelNameText)
                    .addComponent(ModelNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalanceText)
                    .addComponent(BalanceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceText)
                    .addComponent(PriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrintInvoiceButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdministratorDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityText)
                    .addComponent(QuantityChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddToCartButton)
                    .addComponent(LogOutButton)
                    .addComponent(GoBackButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        ShoppingCartText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShoppingCartText.setText("Shopping Cart");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Brand Name", "Model Name", "Price", "Quantity", "Total"
            }
        ));
        ShoppingCartScrollPanel.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShoppingCartScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ShoppingCartText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(AdministratorDetailsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(MainAdministratorTextTop, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainAdministratorTextTop, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdministratorDetailsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ShoppingCartText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShoppingCartScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ItemIDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemIDBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemIDBoxActionPerformed

    private void AddToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartButtonActionPerformed

        try{

        String itemIdStr = ItemIDBox.getText().trim();
        String Addtocarterrorhandelling = PriceBox.getText().trim();ItemNameBox.getText().trim();
        BrandNameBox.getText().trim();ModelNameBox.getText().trim();


        // Check if the fields are not empty and are numeric
        if (itemIdStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Item ID field cannot be empty.");
            return;
        }
        if (Addtocarterrorhandelling.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please press enter before adding to cart.");
            return;
        }

       int itemId = Integer.parseInt(itemIdStr);
       float Addtocart = Float.parseFloat(Addtocarterrorhandelling);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values for Item ID and Quantity.");
        }

        // Check if quantity is zero
        int quantityValue = Integer.parseInt(QuantityChangeButton.getValue().toString());
        if (quantityValue <= 0) {
            JOptionPane.showMessageDialog(this, "Please enter quantity.");
            return; // Exit the method if quantity is zero
        }

        float cost = Float.parseFloat(PriceBox.getText());
        int qty = Integer.parseInt(QuantityChangeButton.getValue().toString());
        float tot = cost * qty;

        df = (DefaultTableModel) jTable1.getModel();
        df.addRow(new Object[]{
            ItemIDBox.getText(), ItemNameBox.getText(), BrandNameBox.getText(), ModelNameBox.getText(), PriceBox.getText(), QuantityChangeButton.getValue().toString(),
            tot

        });

        float sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum = sum + Float.parseFloat(jTable1.getValueAt(i, 6).toString());
        }

        TotalCostBox.setText(String.valueOf(sum));
        ItemIDBox.setText("");
        ItemNameBox.setText("");
        BrandNameBox.setText("");
        ModelNameBox.setText("");
        PriceBox.setText("");
        QuantityChangeButton.setValue(0);
        ItemIDBox.requestFocus();

    }//GEN-LAST:event_AddToCartButtonActionPerformed

    private void ItemIDBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ItemIDBoxKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                String iid = ItemIDBox.getText();
                String query = "SELECT * FROM ITEMS WHERE ItemID = ?";
                pat = con.prepareStatement(query);
                pat.setString(1, iid);
                rs = pat.executeQuery();

                if (rs.next() == false) {
                    JOptionPane.showMessageDialog(this, "Item Not Found");

                } else {
                    String tid = rs.getString("itemid");
                    ItemIDBox.setText(tid.trim());
                    String tname = rs.getString("itemname");
                    ItemNameBox.setText(tname.trim());
                    String bname = rs.getString("brandname");
                    BrandNameBox.setText(bname.trim());
                    String mname = rs.getString("modelname");
                    ModelNameBox.setText(mname.trim());
                    String tprice = rs.getString("price");
                    PriceBox.setText(tprice.trim());
                    QuantityChangeButton.requestFocus();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                Logger.getLogger(ShoppingMain_Administrator.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ItemIDBoxKeyPressed

    private void PrintInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintInvoiceButtonActionPerformed
        // TODO add your handling code here:
        if (PayBox.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the amount to pay.");
            return;
        }

        float tpay = Float.parseFloat(PayBox.getText());
        float tcost = Float.parseFloat(TotalCostBox.getText());

        // Validate if the amount paid is less than the total cost
        if (tpay < tcost) {
            JOptionPane.showMessageDialog(this, "Amount paid should be equal to or greater than the total cost.");
            return;
        }

        // Calculate the balance
        float tbal = tpay - tcost;
        BalanceBox.setText(String.valueOf(tbal));
        
        JOptionPane.showMessageDialog(this, "Balance: " + tbal);

        // Proceed with sales and opening the ShippingInformation frame
        sales();
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShippingInformation().setVisible(true);
            }
        });
    }//GEN-LAST:event_PrintInvoiceButtonActionPerformed


    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:

        Login l = new Login();
        this.hide();
        l.setVisible(true);
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed

        AdministratorItems s = new AdministratorItems();
        this.hide();
        s.setVisible(true);


    }//GEN-LAST:event_GoBackButtonActionPerformed

    private void BalanceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceBoxActionPerformed

    private void TotalCostBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalCostBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalCostBoxActionPerformed

    private void PayBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoppingMain_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoppingMain_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoppingMain_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoppingMain_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShoppingMain_Administrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartButton;
    private javax.swing.JPanel AdministratorDetailsBox;
    private javax.swing.JLabel AdministratorPayText;
    private javax.swing.JTextField BalanceBox;
    private javax.swing.JLabel BalanceText;
    private javax.swing.JLabel BillText;
    private javax.swing.JTextField BrandNameBox;
    private javax.swing.JLabel BrandNameText;
    private javax.swing.JButton GoBackButton;
    private javax.swing.JTextField ItemIDBox;
    private javax.swing.JLabel ItemIDText;
    private javax.swing.JTextField ItemNameBox;
    private javax.swing.JLabel ItemNameText;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JLabel MainAdministratorTextTop;
    private javax.swing.JTextField ModelNameBox;
    private javax.swing.JLabel ModelNameText;
    private javax.swing.JTextField PayBox;
    private javax.swing.JTextField PriceBox;
    private javax.swing.JLabel PriceText;
    private javax.swing.JButton PrintInvoiceButton;
    private javax.swing.JSpinner QuantityChangeButton;
    private javax.swing.JLabel QuantityText;
    private javax.swing.JScrollPane ShoppingCartScrollPanel;
    private javax.swing.JLabel ShoppingCartText;
    private javax.swing.JTextField TotalCostBox;
    private javax.swing.JLabel TotalCostText;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
